### ISSUE TITLE
how to watch files

### ISSUE THREAD

**Issue by ghost** [anheru88/laravel-elixir-browser-sync2#2]
i am wondering how can i define folders to be watch for changes?

**Comment by PMK** [comment]
Hi,
Check this: https://github.com/PMK/laravel-elixir-eslint/blob/master/index.js#L24

So, `new Elixir.Task` returns itself. You can append `watch(globs)`. When you do `$ gulp watch`, this watch function will run (as far as I understood).

See http://laravel.com/docs/5.1/elixir#writing-elixir-extensions, section `Custom Watchers`.

**Comment by ghost** [comment]
thanks for feedback
there is still a problem ,lets say  i wan to chain a sass compiler to it.

```
mix.sass('app.scss','public/assets/css')
             .BrowserSync({
          proxy           : "prod/",
         logPrefix       : "Laravel Eixir BrowserSync",
         logConnections  : false,
         reloadOnRestart : false,
         notify          : true
        });
```

if i run `gulp`,browsersync will work but sass would run only one time 
and if run `gulp watch` sass works but browsersync wont!

**Comment by PMK** [comment]
Hi,

And what will happen if you do this?
mix.sass();
mix.BrowserSync();

This is what I do in my gulpfile.js, because not each extension is returning the mix object. It is not jQuery ;-)

**Comment by ghost** [comment]
@PMK  unfortunatly the same result.is it posible to add a `watch` method to

```
new Task("BrowserSync", function(){
//
})
```

in index file?
when i run `gulp watch` bs will be ignored becuase  the lack of `watch` method .

**Comment by PMK** [comment]
``` javascript
new Task("BrowserSync", function(){
//
}).watch(glob);
```

See http://laravel.com/docs/5.1/elixir#writing-elixir-extensions

**Comment by ghost** [comment]
[15:41:41] Starting 'BrowserSync'...
[15:41:41] 'BrowserSync' errored after 5.58 ms
[15:41:41] TypeError: undefined is not a function
    at Object.init (C:\Users\pooyesh\Desktop\prod\node_modules\laravel-elixir-browsersync2\node_modules\browser-sync\lib\public\ini
t.js:25:25)
    at null.definition (C:\Users\pooyesh\Desktop\prod\node_modules\laravel-elixir-browsersync2\index.js:54:25)
    at Task.run (C:\Users\pooyesh\Desktop\prod\node_modules\laravel-elixir\Task.js:96:17)
    at C:\Users\pooyesh\Desktop\prod\node_modules\laravel-elixir\index.js:88:30
    at Array.forEach (native)
    at Gulp.<anonymous> (C:\Users\pooyesh\Desktop\prod\node_modules\laravel-elixir\index.js:87:22)
    at module.exports (C:\Users\pooyesh\Desktop\prod\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\pooyesh\Desktop\prod\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\pooyesh\Desktop\prod\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\pooyesh\Desktop\prod\node_modules\gulp\node_modules\orchestrator\index.js:134:8)

**Comment by PMK** [comment]
Without the `watch` function, you don't get this problem?

Can you try to put your BrowserSync Task code in a comment and paste this?

``` javascript
new Task('BrowserSync', function() {
    console.log('test');
    return gulp.src('');
})
.watch('./app/**');
```

Try to save any file in the app directory to see if the watch is running.
If this is not working, then something else is broken.

When this is working, can you post your code here (or create a branch so I can take a look into it)?

**Comment by ghost** [comment]
no, 
i tried the code : 

```
C:\Users\pooyesh\Desktop\prod>gulp watch
[17:02:31] Using gulpfile ~\Desktop\prod\gulpfile.js
[17:02:31] Starting 'watch'...
[17:02:31] Finished 'watch' after 216 ms
[17:02:43] Starting 'BrowserSync'...
test
[17:02:43] Finished 'BrowserSync' after 23 ms
```

it seems ok!

**Comment by ghost** [comment]
OK .i found the solution. 
1- put `browserSync.init(options);` outside of `new Task` just before that
2- replace `gulp.watch(src).on("change", browserSync.reload);` with `browserSync.reload()`
3- add `watch(src)` method to `new Task`

now it works like a charm! 
you may also chain it in gulp.js . no need to code separate `mix`

**Comment by PMK** [comment]
Nice!

Looking forward to use it in my projects.

**Comment by PMK** [comment]
Can you push your new code please?

**Comment by amin101** [comment]
hi . see [Pull requesties](https://github.com/anheru88/laravel-elixir-browser-sync2/pulls) . modified code is there
